-- 01_setup.sql
-- Run once as ACCOUNTADMIN in a Snowsight worksheet.
-- Creates the warehouse, database, layer schemas and a role for the pipeline.

USE ROLE ACCOUNTADMIN;

-- smallest size, pauses after 60 seconds of nothing to do
CREATE WAREHOUSE IF NOT EXISTS WH_PIPELINE
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS INSURANCE;
CREATE SCHEMA IF NOT EXISTS INSURANCE.BRONZE;
CREATE SCHEMA IF NOT EXISTS INSURANCE.SILVER;
CREATE SCHEMA IF NOT EXISTS INSURANCE.GOLD;

-- one role does all pipeline work; never use ACCOUNTADMIN from code
CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT USAGE, OPERATE ON WAREHOUSE WH_PIPELINE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE SCHEMA ON DATABASE INSURANCE TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA INSURANCE.BRONZE TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA INSURANCE.SILVER TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA INSURANCE.GOLD TO ROLE TRANSFORMER;

-- replace with the user name you signed up with
GRANT ROLE TRANSFORMER TO USER YOUR_USER_NAME;
ALTER USER YOUR_USER_NAME SET DEFAULT_ROLE = TRANSFORMER, DEFAULT_WAREHOUSE = WH_PIPELINE;

-- a hard stop on spending: suspend the warehouse after 20 credits a month
CREATE RESOURCE MONITOR IF NOT EXISTS RM_MONTHLY
  WITH CREDIT_QUOTA = 20 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE WH_PIPELINE SET RESOURCE_MONITOR = RM_MONTHLY;
